---
title: "Mastermind et permutations"
author: "Kim Antunez, Romain Lesauvage, Alain Quartier-la-Tente"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```


```{r, include=FALSE}
source("../ShinyApp/global.R", encoding="UTF-8",chdir = TRUE)
```


```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
set.seed(1)
```
### m=6 n=4

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
m = 6
n = 4
y=sample(1:m, n, replace = FALSE)
```

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme(y=y, n=n, m=m,maxIters=100,stop_d=TRUE,avec_remise = FALSE)
tableau <- mise_en_forme_tableau(modele, matriciel = TRUE)
tableau
```
  
```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme(y=y, n=n, m=m,maxIters=100,stop_d=TRUE,avec_remise = TRUE)
tableau <- mise_en_forme_tableau(modele, matriciel = TRUE)
tableau
```

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme_hamming(y=y, n=n, m=m,maxIters=100,stop_d=TRUE)
tableau <- mise_en_forme_tableau(modele,matriciel = FALSE)
tableau
```

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme_hamming(y=y, n=n, m=m,maxIters=100,stop_d=TRUE)
tableau <- mise_en_forme_tableau(modele,matriciel = FALSE, N=5*n*m)
tableau
```

### m=6 n=6

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
m = 6
n = 6
y=sample(1:m, n, replace = FALSE)
```

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme(y=y, n=n, m=m,maxIters=100,stop_d=TRUE,avec_remise = FALSE)
tableau <- mise_en_forme_tableau(modele, matriciel = TRUE)
tableau
```
  
```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme(y=y, n=n, m=m,maxIters=100,stop_d=TRUE,avec_remise = TRUE)
tableau <- mise_en_forme_tableau(modele, matriciel = TRUE)
tableau
```

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme_hamming(y=y, n=n, m=m,maxIters=100,stop_d=TRUE)
tableau <- mise_en_forme_tableau(modele,matriciel = FALSE)
tableau
```

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme_hamming(y=y, n=n, m=m,maxIters=100,stop_d=TRUE)
tableau <- mise_en_forme_tableau(modele,matriciel = FALSE, N=5*n*m)
tableau
```
### m=20 n=15

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
m = 20
n = 15
y=sample(1:m, n, replace = FALSE)
```

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme(y=y, n=n, m=m,maxIters=100,stop_d=TRUE,avec_remise = FALSE)
tableau <- mise_en_forme_tableau(modele, matriciel = TRUE)
tableau
```
  
```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme(y=y, n=n, m=m,maxIters=100,stop_d=TRUE,avec_remise = TRUE)
tableau <- mise_en_forme_tableau(modele, matriciel = TRUE)
tableau
```

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme_hamming(y=y, n=n, m=m,maxIters=100,stop_d=TRUE)
tableau <- mise_en_forme_tableau(modele,matriciel = FALSE)
tableau
```

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme_hamming(y=y, n=n, m=m,maxIters=100,stop_d=TRUE)
tableau <- mise_en_forme_tableau(modele,matriciel = FALSE, N=5*n*m)
tableau
```

### m=33 n=30

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
m = 33
n = 30
y=sample(1:m, n, replace = FALSE)
```

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme(y=y, n=n, m=m,maxIters=100,stop_d=TRUE,avec_remise = FALSE)
tableau <- mise_en_forme_tableau(modele, matriciel = TRUE)
tableau
```
  
```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme(y=y, n=n, m=m,maxIters=100,stop_d=TRUE,avec_remise = TRUE)
tableau <- mise_en_forme_tableau(modele, matriciel = TRUE)
tableau
```

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme_hamming(y=y, n=n, m=m,maxIters=100,stop_d=TRUE)
tableau <- mise_en_forme_tableau(modele,matriciel = FALSE)
tableau
```

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme_hamming(y=y, n=n, m=m,maxIters=100,stop_d=TRUE)
tableau <- mise_en_forme_tableau(modele,matriciel = FALSE, N=5*n*m)
tableau
```

### m=33 n=33

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
m = 33
n = 33
y=sample(1:m, n, replace = FALSE)
```

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme(y=y, n=n, m=m,maxIters=100,stop_d=TRUE,avec_remise = FALSE)
tableau <- mise_en_forme_tableau(modele, matriciel = TRUE)
tableau
```
  
```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme(y=y, n=n, m=m,maxIters=100,stop_d=TRUE,avec_remise = TRUE)
tableau <- mise_en_forme_tableau(modele, matriciel = TRUE)
tableau
```

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme_hamming(y=y, n=n, m=m,maxIters=100,stop_d=TRUE)
tableau <- mise_en_forme_tableau(modele,matriciel = FALSE)
tableau
```

```{r, error=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
modele <- lancer_algorithme_hamming(y=y, n=n, m=m,maxIters=100,stop_d=TRUE)
tableau <- mise_en_forme_tableau(modele,matriciel = FALSE, N=5*n*m)
tableau
```


